id = "day-shift"
name = "Day Shift Theme"
schema_version = 1
version = "1.0.0"
authors = ["Jean Tinland"]
description = " A soft theme with light colors for zed"
repository = "https://github.com/Jean-Tinland/zed-theme-day-shift"
